# Generated by Django 4.1 on 2022-08-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverreport',
            name='has_cargo_to_return',
            field=models.BooleanField(default=True, verbose_name='Tem carga para voltar?'),
        ),
    ]
